# Generated by Django 3.1.7 on 2021-08-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210809_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default='%Y/%m/%d'),
        ),
    ]
