# Generated by Django 3.2.6 on 2021-12-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='content',
            field=models.TextField(default='Videos'),
        ),
    ]
