# Generated by Django 3.2.6 on 2021-12-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_youtube_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
    ]
