# Generated by Django 3.2.6 on 2021-12-02 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0023_alter_photo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.fields.related.ForeignKey, to=settings.AUTH_USER_MODEL),
        ),
    ]
