# Generated by Django 3.2.6 on 2022-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_images_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
