# Generated by Django 3.1.7 on 2023-02-22 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20230222_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-id'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='photo',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='content',
            field=models.TextField(default='Youtube video'),
        ),
    ]
