# Generated by Django 3.1.7 on 2023-02-22 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20230222_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
