# Generated by Django 3.1.7 on 2023-02-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_images_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='youtube',
            options={'ordering': ['-date_posted']},
        ),
    ]
