name: Integration workflow
on:
  push:
    branches: ['feature']
  pull_request:
    branches: ['feature']

jobs:
  build:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: localhost
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DEBUG_VALUE: False
      ALLOWED_HOSTS: '*'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      FEATURES: '{ "REVISIT_CASE": true, "EDIT_CASE": true }'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip uninstall boto3
        pip install boto3
        pip uninstall apipkg
        pip install apipkg
        pip install awscli 
        pip uninstall django
        pip install django
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run migrations
      run: python3 manage.py migrate
    - name: Run pytest
      run: |
        pytest
    - name: Lint with flake8
      run: |
        # dont stop the build if there are syntax errors in post
        flake8 blog --count --select=E9,F4,F6,F8 --show-source --statistics
        flake8 person --count --select=E9,F4,F6,F8 --show-source --statistics
